//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int Order_No { get; set; }
        public int Product_ID { get; set; }
        public int Variant_ID { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product_Variant Product_Variant { get; set; }
    }
}
