//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Variant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Variant()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int Product_ID { get; set; }
        public int Variant_ID { get; set; }
        public string Variant_Name { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Units_In_Stock { get; set; }
        public string Image_Path { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Variant Variant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
    }
}
